- name: Install NFS
  apt:
    pkg: 
      - nfs-common
      - nfs-server
- name: Create Share Directory
  file:
    path: /opt/share
    state: directory
    mode: "0755"
- name: Configuration nfs-server
  lineinfile:
    path: /etc/exports
    line: /opt/share *{rw,sync,no_root_squash}
    insertafter: EOF
    create: yes
- name: Restart nfs-server
  service:
    name: nfs-server
    state: restarted
